# Site settings
title: Mason's Journal
author: Mason Everett
baseurl: ""
url: "https://masonheverett.com"
github_username: masonheverett
linkedin_username: masonheverett

# Build settings
theme: minima
plugins:
  - jekyll-feed
exclude:
  - README.md
  - LICENSE
  # Excluded by default
  # - .sass-cache/
  # - .jekyll-cache/
  # - gemfiles/
  # - Gemfile
  # - Gemfile.lock
  # - node_modules/
  # - vendor/bundle/
  # - vendor/cache/
  # - vendor/gems/
  # - vendor/ruby/
