# Site settings
minimal_mistakes_skin: dark
locale: en-US
title: Mason's Journal
subtitle: Never Stop Learning
name: Mason Everett
description: Mason Everett's personal blog for sharing what he is learning from books and other media
url: https://masonheverett.com
baseurl: ""

# Build settings
theme: minimal-mistakes-jekyll
plugins:
  - jekyll-feed
  - jekyll-include-cache
exclude:
  - README.md
  - LICENSE
  # Excluded by default
  # - .sass-cache/
  # - .jekyll-cache/
  # - gemfiles/
  # - Gemfile
  # - Gemfile.lock
  # - node_modules/
  # - vendor/bundle/
  # - vendor/cache/
  # - vendor/gems/
  # - vendor/ruby/
